# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "db/src/schema.rs"
import_types = ["diesel::sql_types::*", "crate::enums::*"]
#custom_type_derives = ["diesel::query_builder::QueryId"]
filter = { except_tables = ["mq_msgs", "mq_payloads"] }
