[package]
name = "pic-store-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
axum = "0.5.7"
base64 = "0.13.0"
biscuit-auth = "2.2.0"
futures = "0.3.21"
http-body = "0.4.5"
ouroboros = "0.15.0"
serde_json = "1.0.81"
thiserror = "1.0.31"
tower = "0.4.13"
tower-cookies = "0.7.0"
tracing = "0.1.35"
uuid = "0.8"
