[package]
name = "pic-store-http-errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
axum = "0.5.7"
http-body = "0.4.5"
serde = "1.0.137"
serde_json = "1.0.81"
thiserror = "1.0.31"
tracing = "0.1.35"
uuid = "0.8"
