[package]
name = "pic-store-convert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
ravif = "0.8.9"
rgb = "0.8.32"
thiserror = "1.0.31"
webp = "0.2.2"
