[package]
name = "pic-store-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.56"
backon = "0.0.2"
opendal = { version = "0.9.0", features = ["retry"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["fs"] }
