[package]
name = "pic-store-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
opendal = { version = "0.8.0", features = ["retry"]}
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["fs"] }
