[package]
name = "pic-store-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pic-store-db = { path = "../db" }

anyhow = "1.0.57"
async-trait = "0.1.56"
aws-sdk-s3 = "0.14.0"
backon = "0.0.2"
http = "0.2.8"
opendal = { version = "0.9.1", features = ["retry"] }
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["fs"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
