[package]
name = "pic-store-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "0.8.0", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-mysql", "sqlx-sqlite", "with-time", "with-uuid"]}
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
time = { version = "0.2", features = ["serde"] }
uuid = "0.8"
