[package]
name = "pic-store-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
axum = "0.5.7"
clap = { version = "3.2.4", features = ["derive", "env", "wrap_help"] }
dotenv = "0.15.0"
log = "0.4.17"
num_cpus = "1.13.1"
opentelemetry = { version= "0.17.0", features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = { version = "0.10.0" }
tokio = { version = "1.19.2", features = [ "full", "test-util" ] }
tonic = "0.6.2"
tracing = "0.1.35"
tracing-bunyan-formatter = "0.3.2"
tracing-honeycomb = "0.4.3"
tracing-log = "0.1.3"
tracing-opentelemetry = "0.17.3"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
