[package]
name = "pic-store-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pic-store-db = { path = "../db" }

anyhow = "1.0.57"
axum = "0.5.7"
clap = { version = "3.2.4", features = ["derive", "env", "wrap_help"] }
dotenv = "0.15.0"
log = "0.4.17"
num_cpus = "1.13.1"
opentelemetry = { version= "0.17.0", features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = { version = "0.10.0" }
sea-orm = { version = "0.8.0", features = ["runtime-tokio-rustls", "sqlx-postgres", "sqlx-mysql", "sqlx-sqlite", "with-time", "with-uuid"]}
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.19.2", features = [ "full", "test-util" ] }
tonic = "0.6.2"
tracing = "0.1.35"
tracing-bunyan-formatter = "0.3.2"
tracing-honeycomb = "0.4.3"
tracing-log = "0.1.3"
tracing-opentelemetry = "0.17.3"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-tree = "0.2.1"
tower = "0.4.12"
uuid = "0.8"
tracing-error = "0.2.0"
color-eyre = "0.6.1"
thiserror = "1.0.31"

[dependencies.tower-http]
version = "0.3.4"
features = [ "catch-panic", "decompression-gzip", "decompression-br", "compression-gzip", "compression-deflate", "limit", "request-id", "trace" ]
